language: php

git:
    submodules: true

php:
  - '7.1'
  - '7.2'

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

install:
  - travis_retry composer install --no-interaction --no-suggest
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar -O coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

before_script:
  - mkdir ./test/logs
  - ls -al
  - sleep 10

script: phpunit --coverage-clover ./test/logs/clover.xml --configuration ./test/phpunit.xml

after_success:
  - travis_retry php coveralls.phar -v